
-- Insert Python terms
INSERT INTO terms (word, slug, ipa, categories, related_terms) VALUES
('decorator', 'decorator', '/ˈdɛkəˌreɪtər/', '{python}', '{function,lambda}'),
('generator', 'generator', '/ˈdʒɛnəˌreɪtər/', '{python}', '{yield,iterate}'),
('comprehension', 'comprehension', '/ˌkɑːmprɪˈhɛnʃən/', '{python}', '{iterate,lambda}'),
('tuple', 'tuple', '/ˈtʌpəl/', '{python}', '{list,dictionary}'),
('dictionary', 'dictionary', '/ˈdɪkʃəˌnɛri/', '{python}', '{tuple,list}'),
('list', 'list', '/lɪst/', '{python,javascript}', '{tuple,dictionary}'),
('slice', 'slice', '/slaɪs/', '{python}', '{list,tuple}'),
('pip', 'pip', '/pɪp/', '{python,cli}', '{import,virtualenv}'),
('virtualenv', 'virtualenv', '/ˈvɜːrtʃuəl ɛnv/', '{python}', '{pip}'),
('self', 'self-python', '/sɛlf/', '{python}', '{class,__init__}'),
('__init__', 'init', '/ɪˈnɪt/', '{python}', '{self-python,class}'),
('class', 'class', '/klæs/', '{python,javascript,typescript}', '{__init__,self-python,inherit}'),
('inherit', 'inherit', '/ɪnˈhɛrɪt/', '{python}', '{class,abstract}'),
('exception', 'exception', '/ɪkˈsɛpʃən/', '{python,java}', '{assert,raise}'),
('raise', 'raise', '/reɪz/', '{python}', '{exception,assert}'),
('try', 'try-except', '/traɪ/', '{python,javascript}', '{exception,raise}'),
('module', 'module', '/ˈmɒdjuːl/', '{python,javascript}', '{import,package}'),
('package', 'package', '/ˈpækɪdʒ/', '{python}', '{module,pip}'),
('docstring', 'docstring', '/ˈdɒkstrɪŋ/', '{python}', '{function,class}'),
('f-string', 'f-string', '/ɛf strɪŋ/', '{python}', NULL),
('mutable', 'mutable', '/ˈmjuːtəbəl/', '{python}', '{immutable,list,tuple}'),
('immutable', 'immutable', '/ɪˈmjuːtəbəl/', '{python}', '{mutable,tuple}'),
('unpacking', 'unpacking', '/ʌnˈpækɪŋ/', '{python}', '{tuple,list}'),
('*args', 'args', '/ɑːrɡz/', '{python}', '{kwargs,function}'),
('**kwargs', 'kwargs', '/ˈkwɑːrɡz/', '{python}', '{args,function}'),
('GIL', 'gil', '/ɡɪl/', '{python}', '{thread}'),
('thread', 'thread', '/θrɛd/', '{python}', '{gil,async}'),
('type hint', 'type-hint', '/taɪp hɪnt/', '{python}', '{function,class}'),
('dataclass', 'dataclass', '/ˈdeɪtəklæs/', '{python}', '{class,decorator}'),
('enumerate', 'enumerate', '/ɪˈnjuːməˌreɪt/', '{python}', '{iterate,list}'),
('zip', 'zip-python', '/zɪp/', '{python}', '{iterate,enumerate}'),
('map', 'map-python', '/mæp/', '{python,javascript}', '{filter,lambda}'),
('filter', 'filter', '/ˈfɪltər/', '{python,javascript}', '{map-python,lambda}'),
('with', 'with-statement', '/wɪð/', '{python}', '{exception}'),
('scope', 'scope', '/skoʊp/', '{python,javascript}', '{global,function}'),
('global', 'global', '/ˈɡloʊbəl/', '{python,javascript}', '{scope}'),
('None', 'none', '/nʌn/', '{python}', '{boolean}'),
('pass', 'pass', '/pæs/', '{python}', '{function,class}'),
('isinstance', 'isinstance', '/ɪz ˈɪnstəns/', '{python}', '{class,type-hint}'),
('property', 'property-python', '/ˈprɒpərti/', '{python}', '{decorator,class,self-python}')
ON CONFLICT (slug) DO NOTHING;
